### ISSUE TITLE
Highchart xAxis is seconds since epoch

### ISSUE THREAD

**Issue by SteveAmor** [bjrhodes/team-dashboard#4]
Can't remember what the xAxis was before but now, it's number of seconds since 1st Jan 1970.

**Comment by bjrhodes** [comment]
This was a change to the angular-highcharts library. Fixed now, although I'm opening a new issue to make things a bit better!

Resolved in commit f3ac0c50834ec6806e5b0a6dc56112bbe0ba72ea
